sudo: required
dist: trusty
before_install:
  - "sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-humanities texlive-science latex-xcolor dvipng texlive-latex-recommended python-pygments"
script:
  - make travis
# TODO: Deploy the built file somewhere (see for instance https://harshjv.github.io/blog/setup-latex-pdf-build-using-travis-ci/)
notifications:
  email: false
